version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"  # Puerto local (8055 por defecto)
    environment:
      - KEY=mi-clave-secreta
      - SECRET=mi-secreto
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=password123
      - DB_CLIENT=sqlite3
      - DB_FILENAME=/data/directus.db
      - CORS_ENABLED=true
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./data:/data
